# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

outerloop_thread <- function(X, y, Z, group, glevel, logodds, sb2, se2, alpha, mu, alpha_jk, pi_k, maxIter, tol, verbose, coreNum) {
    .Call('_bivas_outerloop_thread', PACKAGE = 'bivas', X, y, Z, group, glevel, logodds, sb2, se2, alpha, mu, alpha_jk, pi_k, maxIter, tol, verbose, coreNum)
}

outerloop_mt_thread <- function(Xs, ys, Zs, logodds, sb2, se2, alpha, mu, alpha_jk, pi_k, nn, K, q, maxIter, tol, verbose, coreNum) {
    .Call('_bivas_outerloop_mt_thread', PACKAGE = 'bivas', Xs, ys, Zs, logodds, sb2, se2, alpha, mu, alpha_jk, pi_k, nn, K, q, maxIter, tol, verbose, coreNum)
}

tt <- function(s1, s2, xtx) {
    .Call('_bivas_tt', PACKAGE = 'bivas', s1, s2, xtx)
}

read_data <- function(stringname) {
    .Call('_bivas_read_data', PACKAGE = 'bivas', stringname)
}

